import { images } from "./Images"

export const recipes = [
	{
		title: "Pancakes with syrup and apple slices",
		description:
			"delicious Pancakes with syrup and apple slicesdelicious Pancakes with syrup and apple slicesdelicious Pancakes with syrup and apple slicesdelicious Pancakes with syrup and apple slicesdelicious Pancakes with syrup and apple slicesdelicious Pancakes with syrup and apple slicesdelicious Pancakes with syrup and apple slicesdelicious Pancakes with syrup and apple slicesdelicious Pancakes with syrup and apple slicesdelicious Pancakes with syrup and apple slices",
		image: images.placeholderImage,
		average_score: "4.30",
		difficulty: "easy",
		preparation_time: "5 minutes",
		cooking_time: "30 minutes",
		servings: 12,
		user_id: 2,
		category_id: 2,
	},
	{
		title: "HAMBURGER",
		description: "hamm hamm hamm gur gur gur",
		image: images.placeholderImage,
		average_score: "4.46",
		difficulty: "intermediate",
		preparation_time: "10 minutes",
		cooking_time: "40 minutes",
		servings: 4,
		user_id: 2,
		category_id: 2,
	},
	{
		title: "hotdogg",
		description: "buddy you got that hot dog?",
		image: images.placeholderImage,
		average_score: "4.10",
		difficulty: "easy",
		preparation_time: "5 minutes",
		cooking_time: "30 minutes",
		servings: 6,
		user_id: 2,
		category_id: 2,
	},
	{
		title: "spaghetti",
		description: "delicious spaghetti",
		image: images.placeholderImage,
		average_score: "4.30",
		difficulty: "easy",
		preparation_time: "5 minutes",
		cooking_time: "30 minutes",
		servings: 4,
		user_id: 2,
		category_id: 2,
	},
	{
		title: "Pancakes with syrup and apple slices",
		description: "delicious Pancakes with syrup and apple slices",
		image: images.placeholderImage,
		average_score: "4.30",
		difficulty: "easy",
		preparation_time: "5 minutes",
		cooking_time: "30 minutes",
		servings: 12,
		user_id: 2,
		category_id: 2,
	},
	{
		title: "HAMBURGER",
		description: "hamm hamm hamm gur gur gur",
		image: images.placeholderImage,
		average_score: "4.46",
		difficulty: "intermediate",
		preparation_time: "10 minutes",
		cooking_time: "40 minutes",
		servings: 4,
		user_id: 2,
		category_id: 2,
	},
	{
		title: "hotdogg",
		description: "buddy you got that hot dog?",
		image: images.placeholderImage,
		average_score: "4.10",
		difficulty: "easy",
		preparation_time: "5 minutes",
		cooking_time: "30 minutes",
		servings: 6,
		user_id: 2,
		category_id: 2,
	},
	{
		title: "spaghetti",
		description: "delicious spaghetti",
		image: images.placeholderImage,
		average_score: "4.30",
		difficulty: "easy",
		preparation_time: "5 minutes",
		cooking_time: "30 minutes",
		servings: 4,
		user_id: 2,
		category_id: 2,
	},
	{
		title: "Pancakes with syrup and apple slices",
		description: "delicious Pancakes with syrup and apple slices",
		image: images.placeholderImage,
		average_score: "4.30",
		difficulty: "easy",
		preparation_time: "5 minutes",
		cooking_time: "30 minutes",
		servings: 12,
		user_id: 2,
		category_id: 2,
	},
	{
		title: "HAMBURGER",
		description: "hamm hamm hamm gur gur gur",
		image: images.placeholderImage,
		average_score: "4.46",
		difficulty: "intermediate",
		preparation_time: "10 minutes",
		cooking_time: "40 minutes",
		servings: 4,
		user_id: 2,
		category_id: 2,
	},
	{
		title: "hotdogg",
		description: "buddy you got that hot dog?",
		image: images.placeholderImage,
		average_score: "4.10",
		difficulty: "easy",
		preparation_time: "5 minutes",
		cooking_time: "30 minutes",
		servings: 6,
		user_id: 2,
		category_id: 2,
	},
	{
		title: "spaghetti",
		description: "delicious spaghetti",
		image: images.placeholderImage,
		average_score: "4.30",
		difficulty: "easy",
		preparation_time: "5 minutes",
		cooking_time: "30 minutes",
		servings: 4,
		user_id: 2,
		category_id: 2,
	},
]
